# Generated by Django 3.2.9 on 2021-11-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Товар', max_length=100, verbose_name='product_name')),
                ('description', models.TextField(default='ProductDescription', verbose_name='description')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('type', models.CharField(max_length=30, verbose_name='type')),
                ('weight', models.IntegerField(verbose_name='weight')),
            ],
        ),
    ]
