# Generated by Django 3.2.9 on 2021-11-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0002_auto_20211108_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.BooleanField(default=False, verbose_name='is_admin'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='', max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='', max_length=30, verbose_name='Lastname'),
        ),
    ]
