# Generated by Django 3.2.9 on 2021-11-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='Человек', max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='Неизвестный', max_length=30, verbose_name='Lastname'),
        ),
    ]
