# Generated by Django 3.2.9 on 2021-11-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/static/no_avatar.png', height_field='300', upload_to='static/avatars/', verbose_name='avatar', width_field='300'),
        ),
    ]
