# Generated by Django 3.2.9 on 2021-11-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0008_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/static/no_avatar.png', upload_to='avatars/Y%-%m-%d/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужчина'), ('f', 'Женщина')], default='не указан', max_length=10, verbose_name='Пол'),
        ),
    ]
