# Generated by Django 3.2.9 on 2021-11-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0011_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/static/no_avatar.png', upload_to='avatars/%b%d%Y%H%M%S/', verbose_name='avatar'),
        ),
    ]
